package uascrud;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class uasFormMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form uasFormMainMenu
     */
    public uasFormMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_pg_marketing = new javax.swing.JButton();
        btn_pg_produksi = new javax.swing.JButton();
        btn_pg_personalia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ganbar.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_pg_marketing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/marketing.png"))); // NOI18N
        btn_pg_marketing.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        btn_pg_marketing.setContentAreaFilled(false);
        btn_pg_marketing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pg_marketingActionPerformed(evt);
            }
        });
        jPanel2.add(btn_pg_marketing, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 150, 250));

        btn_pg_produksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/produksi.png"))); // NOI18N
        btn_pg_produksi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        btn_pg_produksi.setContentAreaFilled(false);
        btn_pg_produksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pg_produksiActionPerformed(evt);
            }
        });
        jPanel2.add(btn_pg_produksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 150, 250));

        btn_pg_personalia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/personalia.png"))); // NOI18N
        btn_pg_personalia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        btn_pg_personalia.setContentAreaFilled(false);
        btn_pg_personalia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pg_personaliaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_pg_personalia, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 150, 250));

        jLabel1.setFont(new java.awt.Font("Poppins Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("E-Inventori Office");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        btn_logout.setFont(new java.awt.Font("Poppins", 1, 15)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("Logout");
        btn_logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btn_logout.setContentAreaFilled(false);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel2.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 500, 45));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bg2.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pg_produksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pg_produksiActionPerformed
        // TODO add your handling code here:
        try{
            uasFormProduksi pro = new uasFormProduksi();
            pro.setVisible(true);
            this.setVisible(false);
        }catch(SQLException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btn_pg_produksiActionPerformed

    private void btn_pg_marketingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pg_marketingActionPerformed
        // TODO add your handling code here:
        try{
            uasFormMarketing mar = new uasFormMarketing();
            mar.setVisible(true);
            this.setVisible(false);
        }catch(SQLException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btn_pg_marketingActionPerformed

    private void btn_pg_personaliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pg_personaliaActionPerformed
        // TODO add your handling code here:
        try{
            uasFormPersonalia per = new uasFormPersonalia();
            per.setVisible(true);
            this.setVisible(false);
        }catch(SQLException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btn_pg_personaliaActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        uasLogin bb = new uasLogin();
        if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan Logout?","Warning",2)== JOptionPane.YES_OPTION){
            bb.Logout(uasSession.getUserID());
            uasFormLogin m = new uasFormLogin();
            m.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_pg_marketing;
    private javax.swing.JButton btn_pg_personalia;
    private javax.swing.JButton btn_pg_produksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
