package uascrud;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class uasFormProduksi extends javax.swing.JFrame {
    private DefaultTableModel tabmode;
    private ResultSet hasil;
    
    uasCrudProduksi aa = new uasCrudProduksi();
    
    public uasFormProduksi() throws SQLException{
        initComponents();
        tampil_database();
    }
    
    public void tampil_database(){
        Object [] baris = {"ID Barang","Nama Barang","Tgl Masuk Barang","Jumlah Barang","Harga Satuan Barang","Harga Total Barang","Jumlah Barang Tersedia","Jumlah Barang Away","Tgl Keluar Barang"};
        tabmode = new DefaultTableModel(null, baris);
        tabel_marketing.setModel(tabmode);
        try {
            hasil = aa.tampilData();
            while(hasil.next()){
                aa.setIdBarang(hasil.getString("idBarang"));
                aa.setNamaBarang(hasil.getString("namaBarang"));
                aa.setTglMasuk(hasil.getString("tglMasuk"));
//                aa.setJumlahBarang(hasil.getString("jumlahBarang"));
//                aa.setHargaSatuan(hasil.getString("hargaSatuan"));
//                aa.setHargaTotal(hasil.getString("hargaTotal"));
                aa.setJumlahBarang(hasil.getDouble("jumlahBarang"));
                aa.setHargaSatuan(hasil.getDouble("hargaSatuan"));
//                aa.setHargaTotal(hasil.getDouble("harga_total"));
                aa.setHargaTotal(hasil.getDouble("jumlahBarang"), hasil.getDouble("hargaSatuan"));
//                aa.setHargaTotal();
                aa.setBarangHadir(hasil.getDouble("barangHadir"));
                aa.setBarangAway(hasil.getDouble("jumlahBarang"), hasil.getDouble("barangHadir"));
                aa.setTglKeluar(hasil.getString("tglKeluar"));
                
//                aa.setID(hasil.getString("id"));
//                aa.setNama(hasil.getString("nama"));
//                aa.setAlamat(hasil.getString("alamat"));
                String[] data = {aa.getIdBarang(), aa.getNamaBarang(), aa.getTglMasuk(), Double.toString(aa.getJumlahBarang()), Double.toString(aa.getHargaSatuan()), Double.toString(aa.getHargaTotal()), Double.toString(aa.getBarangHadir()), Double.toString(aa.getBarangAway()), aa.getTglKeluar()};
//                String[] data = {aa.getIdBarang(), aa.getNamaBarang(), aa.getTglMasuk(), aa.getJumlahBarang(), aa.getHargaSatuan(), aa.getHargaTotal(), aa.barangHadir, aa.barangAway, aa.getTglKeluar()};
                tabmode.addRow(data);
            }
        } catch (Exception e){
            
        }
    }
    
    
    public void reset_text(){
        txt_id.setText("");
        txt_nm.setText("");
        txt_msk.setText("");
        txt_jml.setText("");
        txt_hst.setText("");
        txt_htl.setText("");
        txt_bts.setText("");
        txt_bwy.setText("");
        txt_klr.setText("");
    }
    
    public void reset_cari(){
        txt_cari.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_reset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_ubah = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btn_cari = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_smdt = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        btn_total = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_nm = new javax.swing.JTextField();
        txt_msk = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_marketing = new javax.swing.JTable();
        txt_jml = new javax.swing.JTextField();
        txt_hst = new javax.swing.JTextField();
        txt_htl = new javax.swing.JTextField();
        txt_bts = new javax.swing.JTextField();
        txt_bwy = new javax.swing.JTextField();
        txt_klr = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_item = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_hitung = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        btn_htwy = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tgl Masuk Barang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 210, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jumlah Barang");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 275, -1, -1));

        btn_reset.setForeground(new java.awt.Color(255, 255, 255));
        btn_reset.setText("Reset");
        btn_reset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_reset.setContentAreaFilled(false);
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 485, 100, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Harga Satuan Barang");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 341, -1, -1));

        txt_cari.setForeground(new java.awt.Color(255, 255, 255));
        txt_cari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_cari.setOpaque(false);
        getContentPane().add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(763, 21, 250, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Harga Total Barang");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 403, -1, -1));

        btn_ubah.setForeground(new java.awt.Color(255, 255, 255));
        btn_ubah.setText("Ubah");
        btn_ubah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_ubah.setContentAreaFilled(false);
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 485, 100, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jumlah Barang Tersedia");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 82, -1, -1));

        btn_cari.setForeground(java.awt.Color.white);
        btn_cari.setText("Cari Data");
        btn_cari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_cari.setContentAreaFilled(false);
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, 100, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Jumlah Barang Away");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 146, -1, -1));

        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("Hapus");
        btn_hapus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_hapus.setContentAreaFilled(false);
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 485, 100, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Barang");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 82, -1, -1));

        btn_smdt.setForeground(java.awt.Color.white);
        btn_smdt.setText("Semua Data");
        btn_smdt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_smdt.setContentAreaFilled(false);
        btn_smdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_smdtActionPerformed(evt);
            }
        });
        getContentPane().add(btn_smdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1127, 20, 125, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tgl Keluar Barang");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 210, -1, -1));

        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("Kembali");
        btn_back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_back.setContentAreaFilled(false);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 20, 80, 30));

        btn_total.setForeground(new java.awt.Color(255, 255, 255));
        btn_total.setText("Total");
        btn_total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_total.setContentAreaFilled(false);
        btn_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_totalActionPerformed(evt);
            }
        });
        getContentPane().add(btn_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 399, 100, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Pencarian");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 24, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Jumlah Item Inventori");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1336, 24, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inventori Divisi Produksi");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 13, -1, -1));

        txt_nm.setForeground(new java.awt.Color(255, 255, 255));
        txt_nm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_nm.setOpaque(false);
        txt_nm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nmActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 143, 250, -1));

        txt_msk.setForeground(new java.awt.Color(255, 255, 255));
        txt_msk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_msk.setOpaque(false);
        getContentPane().add(txt_msk, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 207, 250, -1));

        tabel_marketing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_marketing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_marketingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_marketing);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 79, 610, -1));

        txt_jml.setForeground(new java.awt.Color(255, 255, 255));
        txt_jml.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_jml.setOpaque(false);
        getContentPane().add(txt_jml, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 272, 250, -1));

        txt_hst.setForeground(new java.awt.Color(255, 255, 255));
        txt_hst.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_hst.setOpaque(false);
        getContentPane().add(txt_hst, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 338, 250, -1));

        txt_htl.setForeground(new java.awt.Color(255, 255, 255));
        txt_htl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_htl.setOpaque(false);
        getContentPane().add(txt_htl, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 400, 250, -1));

        txt_bts.setForeground(new java.awt.Color(255, 255, 255));
        txt_bts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_bts.setOpaque(false);
        getContentPane().add(txt_bts, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 79, 250, -1));

        txt_bwy.setForeground(new java.awt.Color(255, 255, 255));
        txt_bwy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_bwy.setOpaque(false);
        getContentPane().add(txt_bwy, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 143, 250, -1));

        txt_klr.setForeground(new java.awt.Color(255, 255, 255));
        txt_klr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_klr.setOpaque(false);
        txt_klr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_klrActionPerformed(evt);
            }
        });
        getContentPane().add(txt_klr, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 207, 250, -1));

        txt_id.setForeground(new java.awt.Color(255, 255, 255));
        txt_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_id.setOpaque(false);
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 79, 250, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Barang");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, -1, -1));

        txt_item.setForeground(java.awt.Color.white);
        txt_item.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_item.setOpaque(false);
        getContentPane().add(txt_item, new org.netbeans.lib.awtextra.AbsoluteConstraints(1465, 21, 86, -1));

        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setText("Simpan");
        btn_simpan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_simpan.setContentAreaFilled(false);
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 485, 100, -1));

        btn_hitung.setForeground(java.awt.Color.white);
        btn_hitung.setText("Hitung");
        btn_hitung.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_hitung.setContentAreaFilled(false);
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(1558, 20, 70, -1));

        btn_keluar.setForeground(new java.awt.Color(255, 255, 255));
        btn_keluar.setText("Keluar");
        btn_keluar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_keluar.setContentAreaFilled(false);
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 485, 100, -1));

        btn_htwy.setForeground(new java.awt.Color(255, 255, 255));
        btn_htwy.setText("Hitung");
        btn_htwy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_htwy.setContentAreaFilled(false);
        btn_htwy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_htwyActionPerformed(evt);
            }
        });
        getContentPane().add(btn_htwy, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 142, 60, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/produksi baru.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 350, 350));

        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/marketing 1.png"))); // NOI18N
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1640, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        reset_text();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        if (txt_id.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, ID Barang belum diisi !");
            txt_id.requestFocus();
        } else if (txt_nm.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Nama Barang belum diisi !");
            txt_nm.requestFocus();
        } else if (txt_msk.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Tanggal Masuk Barang belum diisi !");
            txt_msk.requestFocus();
        } else if (txt_jml.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Jumlah Barang belum diisi !");
            txt_jml.requestFocus();
        } else if (txt_hst.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Harga Satuan Barang belum diisi !");
            txt_hst.requestFocus();
        } else if (txt_htl.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Harga Total Barang belum diisi !");
            txt_htl.requestFocus();
        } else if (txt_bts.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Jumlah Barang Tersedia belum diisi !");
            txt_bts.requestFocus();
        } else if (txt_bwy.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Jumlah Barang Away belum diisi !");
            txt_bwy.requestFocus();
        } else if (txt_klr.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Tanggal Keluar Barang belum diisi !");
            txt_klr.requestFocus();
        } else {
            try{
                aa.setIdBarang(txt_id.getText());
                aa.setNamaBarang(txt_nm.getText());
                aa.setTglMasuk(txt_msk.getText());
                aa.setJumlahBarang(Double.parseDouble(txt_jml.getText()));
                aa.setHargaSatuan(Double.parseDouble(txt_hst.getText()));
                //                aa.setHargaTotal(Double.parseDouble(txt_htl.getText()));
                //                aa.setHargaTotal();
                aa.setHargaTotal(Double.parseDouble(txt_jml.getText()), Double.parseDouble(txt_jml.getText()));
                aa.setBarangHadir(Double.parseDouble(txt_bts.getText()));
                aa.setBarangAway(Double.parseDouble(txt_jml.getText()), Double.parseDouble(txt_bts.getText()));
                aa.setTglKeluar(txt_klr.getText());

                aa.ubahData(aa.getIdBarang(), aa.getNamaBarang(), aa.getTglMasuk(), aa.getJumlahBarang(), aa.getHargaSatuan(), aa.getHargaTotal(), aa.getBarangHadir(), aa.getBarangAway(), aa.getTglKeluar());

                JOptionPane.showMessageDialog(null, "Data berhasil diubah" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
                tampil_database();
                reset_text();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Data gagal diubah" , "Informasi",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        //sukses
        Object [] baris = {"ID Barang","Nama Barang","Tgl Masuk Barang","Jumlah Barang","Harga Satuan Barang","Harga Total Barang","Jumlah Barang Tersedia","Jumlah Barang Away","Tgl Keluar Barang"};
        tabmode = new DefaultTableModel(null, baris);
        tabel_marketing.setModel(tabmode);
        try {
            hasil = aa.cariData(txt_cari.getText());
            //            hasil = aa.cariDatax(txt_cari.getText());

            while(hasil.next()){
                aa.setIdBarang(hasil.getString("idBarang"));
                aa.setNamaBarang(hasil.getString("namaBarang"));
                aa.setTglMasuk(hasil.getString("tglMasuk"));
                //                aa.setJumlahBarang(hasil.getString("jumlahBarang"));
                //                aa.setHargaSatuan(hasil.getString("hargaSatuan"));
                //                aa.setHargaTotal(hasil.getString("hargaTotal"));
                aa.setJumlahBarang(hasil.getDouble("jumlahBarang"));
                aa.setHargaSatuan(hasil.getDouble("hargaSatuan"));
                //                aa.setHargaTotal(hasil.getDouble("harga_total"));
                aa.setHargaTotal(hasil.getDouble("jumlahBarang"), hasil.getDouble("hargaSatuan"));
                //                aa.setHargaTotal();
                aa.setBarangHadir(hasil.getDouble("barangHadir"));
                aa.setBarangAway(hasil.getDouble("jumlahBarang"), hasil.getDouble("barangHadir"));
                aa.setTglKeluar(hasil.getString("tglKeluar"));

                //                aa.setID(hasil.getString("id"));
                //                aa.setNama(hasil.getString("nama"));
                //                aa.setAlamat(hasil.getString("alamat"));
                String[] data = {aa.getIdBarang(), aa.getNamaBarang(), aa.getTglMasuk(), Double.toString(aa.getJumlahBarang()), Double.toString(aa.getHargaSatuan()), Double.toString(aa.getHargaTotal()), Double.toString(aa.getBarangHadir()), Double.toString(aa.getBarangAway()), aa.getTglKeluar()};
                tabmode.addRow(data);
            }
            JOptionPane.showMessageDialog(null,"Data berhasil ditemukan!");
        } catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
        }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        if (txt_id.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, ID belum diisi !");
            txt_id.requestFocus();
        } else {
            if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan menghapus dataini ?","Warning",2) == JOptionPane.YES_OPTION){
                String id = "";
                try {
                    aa.setIdBarang(txt_id.getText());
                    aa.hapusData(aa.getIdBarang());
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus" , "Informasi",JOptionPane.INFORMATION_MESSAGE);
                    tampil_database();
                    reset_text();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Data gagal dihapus" , "Informasi",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_smdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_smdtActionPerformed
        // TODO add your handling code here:
        Object [] baris = {"ID Barang","Nama Barang","Tgl Masuk Barang","Jumlah Barang","Harga Satuan Barang","Harga Total Barang","Jumlah Barang Tersedia","Jumlah Barang Away","Tgl Keluar Barang"};
        tabmode = new DefaultTableModel(null, baris);
        tabel_marketing.setModel(tabmode);
        try {
            hasil = aa.tampilData();
            while(hasil.next()){
                aa.setIdBarang(hasil.getString("idBarang"));
                aa.setNamaBarang(hasil.getString("namaBarang"));
                aa.setTglMasuk(hasil.getString("tglMasuk"));
                //                aa.setJumlahBarang(hasil.getString("jumlahBarang"));
                //                aa.setHargaSatuan(hasil.getString("hargaSatuan"));
                //                aa.setHargaTotal(hasil.getString("hargaTotal"));
                aa.setJumlahBarang(hasil.getDouble("jumlahBarang"));
                aa.setHargaSatuan(hasil.getDouble("hargaSatuan"));
                //                aa.setHargaTotal(hasil.getDouble("harga_total"));
                aa.setHargaTotal(hasil.getDouble("jumlahBarang"), hasil.getDouble("hargaSatuan"));
                //                aa.setHargaTotal();
                aa.setBarangHadir(hasil.getDouble("barangHadir"));
                aa.setBarangAway(hasil.getDouble("jumlahBarang"), hasil.getDouble("barangHadir"));
                aa.setTglKeluar(hasil.getString("tglKeluar"));

                //                aa.setID(hasil.getString("id"));
                //                aa.setNama(hasil.getString("nama"));
                //                aa.setAlamat(hasil.getString("alamat"));
                String[] data = {aa.getIdBarang(), aa.getNamaBarang(), aa.getTglMasuk(), Double.toString(aa.getJumlahBarang()), Double.toString(aa.getHargaSatuan()), Double.toString(aa.getHargaTotal()), Double.toString(aa.getBarangHadir()), Double.toString(aa.getBarangAway()), aa.getTglKeluar()};
                //                String[] data = {aa.getIdBarang(), aa.getNamaBarang(), aa.getTglMasuk(), aa.getJumlahBarang(), aa.getHargaSatuan(), aa.getHargaTotal(), aa.barangHadir, aa.barangAway, aa.getTglKeluar()};
                tabmode.addRow(data);
            }
            reset_cari();
        } catch (Exception e){

        }
    }//GEN-LAST:event_btn_smdtActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
                uasFormMainMenu m = new uasFormMainMenu();
                m.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_totalActionPerformed
        // TODO add your handling code here:
        if (txt_jml.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Jumlah Barang belum diisi !");
            txt_jml.requestFocus();
        } else if (txt_hst.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Harga Satuan Barang belum diisi !");
            txt_hst.requestFocus();
        } else{
            String jml = txt_jml.getText();
            Double jumlah = Double.parseDouble(jml);

            String hst = txt_hst.getText();
            Double satuan = Double.parseDouble(hst);

            aa.setHargaTotal(jumlah, satuan);
            //            aa.setHargaTotal();
            txt_htl.setText(String.valueOf(aa.getHargaTotal()));
            //            cetakTotal(aa.getHargaTotal());
        }
        //        try {
            //            aa.setHargaTotal(Double.parseDouble(txt_htl.getText()));
            //            txt_htl.setText(String.valueOf(aa.getHargaTotal()));
            //
            //        } catch (Exception e){
            //            System.out.println(e);
            //        }

    }//GEN-LAST:event_btn_totalActionPerformed

    private void txt_nmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nmActionPerformed

    private void tabel_marketingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_marketingMouseClicked
        // TODO add your handling code here:
        try{
            int row = tabel_marketing.rowAtPoint(evt.getPoint());

            //             "ID Barang","Nama Barang","Tgl Masuk Barang","Jumlah Barang","Harga Satuan Barang","Harga Total Barang","Jumlah Barang Tersedia","Jumlah Barang Keluar","Tgl Keluar Barang"
            String idBarang = tabel_marketing.getValueAt(row, 0).toString();
            String namaBarang = tabel_marketing.getValueAt(row, 1).toString();
            String tgl_masuk = tabel_marketing.getValueAt(row, 2).toString();

            String jumlah_barang = tabel_marketing.getValueAt(row, 3).toString();
            String harga_satuan = tabel_marketing.getValueAt(row, 4).toString();
            String harga_total = tabel_marketing.getValueAt(row, 5).toString();

            String barang_hadir = tabel_marketing.getValueAt(row, 6).toString();
            String barang_away = tabel_marketing.getValueAt(row, 7).toString();
            String tgl_keluar = tabel_marketing.getValueAt(row, 8).toString();

            txt_id.setText(String.valueOf(idBarang));
            txt_nm.setText(String.valueOf(namaBarang));
            txt_msk.setText(String.valueOf(tgl_masuk));
            txt_jml.setText(String.valueOf(jumlah_barang));
            txt_hst.setText(String.valueOf(harga_satuan));
            txt_htl.setText(String.valueOf(harga_total));
            txt_bts.setText(String.valueOf(barang_hadir));
            txt_bwy.setText(String.valueOf(barang_away));
            txt_klr.setText(String.valueOf(tgl_keluar));
        }catch(Exception e){
        }
    }//GEN-LAST:event_tabel_marketingMouseClicked

    private void txt_klrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_klrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_klrActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        if (txt_id.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, ID Barang belum diisi !");
            txt_id.requestFocus();
        } else if (txt_nm.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Nama Barang belum diisi !");
            txt_nm.requestFocus();
        } else if (txt_msk.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Tanggal Masuk Barang belum diisi !");
            txt_msk.requestFocus();
        } else if (txt_jml.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Jumlah Barang belum diisi !");
            txt_jml.requestFocus();
        } else if (txt_hst.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Harga Satuan Barang belum diisi !");
            txt_hst.requestFocus();
        } else if (txt_htl.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Harga Total Barang belum diisi !");
            txt_htl.requestFocus();
        } else if (txt_bts.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Jumlah Barang Tersedia belum diisi !");
            txt_bts.requestFocus();
        } else if (txt_bwy.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Jumlah Barang Away belum diisi !");
            txt_bwy.requestFocus();
        } else if (txt_klr.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Tanggal Keluar Barang belum diisi !");
            txt_klr.requestFocus();
        } else {
            try {
                aa.setIdBarang(txt_id.getText());
                //                System.out.println(aa.getIdBarang());
                aa.setNamaBarang(txt_nm.getText());
                aa.setTglMasuk(txt_msk.getText());
                //                aa.setJumlahBarang(Double.toString(txt_jml.getText()));
                aa.setJumlahBarang(Double.parseDouble(txt_jml.getText()));
                aa.setHargaSatuan(Double.parseDouble(txt_hst.getText()));
                aa.setHargaTotal(Double.parseDouble(txt_jml.getText()), Double.parseDouble(txt_jml.getText()));
                //                aa.setHargaTotal();
                //                aa.setJumlahBarang(txt_jml.getText());
                //                aa.setHargaSatuan(txt_hst.getText());
                //                aa.setHargaTotal(txt_htl.getText());
                aa.setBarangHadir(Double.parseDouble(txt_bts.getText()));
                aa.setBarangAway(Double.parseDouble(txt_jml.getText()), Double.parseDouble(txt_bts.getText()));
                aa.setTglKeluar(txt_klr.getText());

                aa.simpanData(aa.getIdBarang(), aa.getNamaBarang(), aa.getTglMasuk(), aa.getJumlahBarang(), aa.getHargaSatuan(), aa.getHargaTotal(), aa.getBarangHadir(), aa.getBarangAway(), aa.getTglKeluar());

                JOptionPane.showMessageDialog(null, "Data berhasil tersimpan" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
                tampil_database();
                reset_text();
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Data gagal tersimpan" , "Informasi",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungActionPerformed
        // TODO add your handling code here:
        try {
            hasil = aa.hitungData();
            if(hasil.next()){
                String count = hasil.getString("count(*)");
                txt_item.setText(count);
            }
        } catch (Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_hitungActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan keluar ?","Warning",2)== JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_htwyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_htwyActionPerformed
        // TODO add your handling code here:
        if (txt_bts.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Jumlah Barang belum diisi !");
            txt_bts.requestFocus();
        } else{
            String brg = txt_jml.getText();
            Double jumlahBarang = Double.parseDouble(brg);

            String ada = txt_bts.getText();
            Double hadir = Double.parseDouble(ada);

            aa.setBarangAway(jumlahBarang, hadir);
            //            aa.setHargaTotal();
            txt_bwy.setText(String.valueOf(aa.getBarangAway()));
        }
    }//GEN-LAST:event_btn_htwyActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_hitung;
    private javax.swing.JButton btn_htwy;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_smdt;
    private javax.swing.JButton btn_total;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_marketing;
    private javax.swing.JTextField txt_bts;
    private javax.swing.JTextField txt_bwy;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_hst;
    private javax.swing.JTextField txt_htl;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_item;
    private javax.swing.JTextField txt_jml;
    private javax.swing.JTextField txt_klr;
    private javax.swing.JTextField txt_msk;
    private javax.swing.JTextField txt_nm;
    // End of variables declaration//GEN-END:variables
}
